#!/usr/bin/env python3
"""Convert Lua files to embedded C++ at build time."""

import os
import sys

def find_delim(content: str) -> str:
    delim = "LUA"
    while f"){delim}\"" in content:
        delim += "LUA"
    return delim

def generate(input_dir: str, output: str) -> None:
    files: list[str] = sorted(
        f for f in os.listdir(input_dir) if f.endswith(".lua")
    )
    guard = "EMBEDDED_LUA_HPP"

    lines: list[str] = [
        f"// generated by embed_lua.py - do not edit",
        f"#pragma once",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f'#include <lua.hpp>',
        f'#include <string_view>',
        f"",
        f"namespace LunarCore {{",
        f"namespace EmbeddedLua {{",
        f"",
    ]

    for filename in files:
        module = filename[:-4]  # strip .lua
        var = f"lua_{module}"
        path = os.path.join(input_dir, filename)
        with open(path) as f:
            content = f.read()
        delim = find_delim(content)
        lines.append(f'inline constexpr const char {var}[] = R"{delim}(')
        lines.append(content)
        if not content.endswith("\n"):
            lines.append("")
        lines.append(f'){delim}";')
        lines.append(f"inline constexpr std::string_view {var}_sv({var}, sizeof({var}) - 1);")
        lines.append("")

    lines.append("inline void register_all(lua_State* L) {")
    for filename in files:
        module = filename[:-4]
        var = f"lua_{module}"
        lines.append(f'    lua_getfield(L, LUA_REGISTRYINDEX, "lunar_modules");')
        lines.append(f"    if (luaL_loadbuffer(L, {var}_sv.data(), {var}_sv.size(), \"lunar/{module}\") == LUA_OK) {{")
        lines.append(f"        if (lua_pcall(L, 0, 1, 0) == LUA_OK && lua_istable(L, -1)) {{")
        lines.append(f'            lua_setfield(L, -2, "lunar/{module}");')
        lines.append(f"        }} else {{")
        lines.append(f"            lua_pop(L, 1);")
        lines.append(f"        }}")
        lines.append(f"    }} else {{")
        lines.append(f"        lua_pop(L, 1);")
        lines.append(f"    }}")
        lines.append(f"    lua_pop(L, 1);")
    lines.append("}")

    lines.extend([
        f"",
        f"}} // namespace EmbeddedLua",
        f"}} // namespace LunarCore",
        f"",
        f"#endif // {guard}",
        f"",
    ])

    with open(output, "w") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_dir> <output_header>", file=sys.stderr)
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
